### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by TheDoggoRex** [DiscordStyles/RadialStatus#24]
Not sure if this is just a local issue, or if discord did a new update that broke it, but I have the theme enabled and the status' are just normal. I tried re-downloading it a few times and it didn't fix.

If it's just a me issue, then sorry for the bother.

**Comment by Tracenji** [comment]
also not working for me
probably a discord update

**Comment by Tracenji** [comment]
actually, after looking at it, the import URL is wrong, probably because of the new repo structure 

if you open the theme file in notepad or something and replace 
`@import url("https://discordstyles.github.io/RadialStatus/base.css");`
with
`@import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css");`
then it works again

probably a oversight by the creator or betterdiscord.app could be taking a long time to update to the new theme file

**Comment by TheDoggoRex** [comment]
Oh thanks! Just checked back, did that fix and it worked :smile:

**Comment by Gibbu** [comment]
The website doesn't know how to detect if the `.theme.css` file has changed. I'm working on that now. Sorry about that :\
